name: q3c

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  tester:
    name: Test the code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
        PGVERSION: [11, 12, 13]
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: PG setup
        run: |
          sudo apt-get -y --purge remove postgresql libpq-dev libpq5 postgresql-client-common postgresql-common
          sudo apt-get -y install python3 python3-pip lcov
          sudo rm -rf /var/lib/postgresql
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo sh -c "echo deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main ${{ matrix.PGVERSION }} >> /etc/apt/sources.list.d/postgresql.list"
          sudo sh -c "echo deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg-testing main ${{ matrix.PGVERSION }} >> /etc/apt/sources.list.d/postgresql.list"
          sudo apt-get update -qq
          sudo apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::="--force-confnew" install postgresql-${{ matrix.PGVERSION }} postgresql-server-dev-$PGVERSION
          sudo chmod 777 /etc/postgresql/${{ matrix.PGVERSION}}/main/pg_hba.conf
          sudo echo "local   all         postgres                          trust" > /etc/postgresql/$PGVERSION/main/pg_hba.conf
          sudo echo "local   all         all                               trust" >> /etc/postgresql/${{ matrix.PGVERSION }}/main/pg_hba.conf
          sudo echo "host    all         all         127.0.0.1/32          trust" >> /etc/postgresql/${{ matrix.PGVERSION }}/main/pg_hba.conf
          sudo echo "host    all         all         ::1/128               trust" >> /etc/postgresql/${{ matrix.PGVERSION }}/main/pg_hba.conf
          sudo /etc/init.d/postgresql restart
          # if [[ ${COVERAGE} == 1 ]] ; then sudo /etc/init.d/postgresql stop ; fi
          sudo pip install cpp-coveralls

          
